swagger: '2.0'
info:
  version: '1.3'
  title: 'Operator Management UI API'
  description: 'API Operator Management exposes to UI/Middleware use'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /dhr/OperatorManagementUIApi/1.3
schemes:
 - https

securityDefinitions:
  BasicAuth:
    type: basic
    description: HTTP Basic Auth

  apiKeyUser:
    type: apiKey
    name: "Api-Key-User"
    description: "Defines user that is performing operations. Possible user's are MyData Account Owner's"
    in: header

paths:
  /slr/account/{account_id}/service/{service_id}:
    get:
      security:
        - apiKeyUser: []
      tags:
      - "Service Linking"
      description: "Entrypoint for creating new SLR with service.\nWill take UUID\
        \ of service to link with as paramater. Returns redirect to Service Login. This endpoint will start chain of events."
      summary: "Start Process of creating SLR"
      parameters:
      - name: "account_id"
        in: "path"
        description: "Unique ID of user initiating process."
        required: true
        type: "string"
        format: "uuid4"
      - name: "service_id"
        in: "path"
        description: "Unique ID of service to make SLR with."
        required: true
        type: "string"
        format: "uuid4"
      responses:
        302:
          description: "Returns Redirect to Service Login page for authentication."
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        504:
          description: "Gateway Timeout"
          schema:
            $ref: "#/definitions/errors"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /slr/account/{account_id}/service/{service_id}/slr/{link_id}:
    post:
      security:
        - apiKeyUser: []
      tags:
      - "Service Linking"
      description: "Endpoint for Disabling Active SLR."
      summary: "Disable an active SLR"
      parameters:
      - name: "account_id"
        in: "path"
        description: "Unique ID of user initiating process."
        required: true
        type: "string"
        format: "uuid4"
      - name: "service_id"
        in: "path"
        description: "Unique ID of service to make SLR with."
        required: true
        type: "string"
        format: "uuid4"
      - name: "link_id"
        in: "path"
        description: "Unique ID of Service Link"
        required: true
        type: "string"
        format: "uuid4"
      responses:
        200:
          description: "Returns Created SSR signifying the status change to Disabled."
          schema:
            $ref: "#/definitions/SSR"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        504:
          description: "Gateway Timeout"
          schema:
            $ref: "#/definitions/errors"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /cr/consent_form/account/{account_id}:
    # This is a HTTP operation
    get:
      tags:
      - "Consent Management"
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Consent Form` template.
      summary: "Fetch Consent Form"
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: source
          in: query
          description: source id
          required: true
          type: string

        -
          name: sink
          in: query
          description: sink id
          required: true
          type: string

        -
          name: "account_id"
          in: "path"
          required: true
          type: string
          description: "account id"

      # Expected responses for this operation:
      responses:
        200:
          description: "Returns 200 OK"
          schema:
            $ref: "#/definitions/Consent_FormReply"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"

    post:
      tags:
      - "Consent Management"
      # Describe this verb here. Note: you can use markdown
      description: "Post filled `Consent Form`"
      summary: "Post filled Consent Form"
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: source
          in: query
          description: source id
          required: true
          type: string

        -
          name: sink
          in: query
          description: sink id
          required: true
          type: string
        -
          name: "account_id"
          in: "path"
          required: true
          type: string
          description: "account id"
        -
          in: "body"
          name: "body"
          description: "User filled Consent Form"
          required: true
          schema:
            $ref: "#/definitions/Consent_FormReply"
      # Expected responses for this operation:
      responses:
        201:
          description: "returns CR id's of created consent"
          schema:
            $ref: '#/definitions/ConsentFormPOSTReply'
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"

  /cr/account_id/{acc_id}/service/{srv_id}/consent/{cr_id}/status/{new_status}:
    post:
      tags:
      - "Consent Management"
      description: "Change status of consent"
      summary: "Change consent status"
      parameters:
      - name: "acc_id"
        in: "path"
        description: "User's MyData Account ID"
        required: true
        type: "string"
      - name: "srv_id"
        in: "path"
        description: "Unique ID of service id"
        required: true
        type: "string"
      - name: "cr_id"
        in: "path"
        description: "Unique ID of consent record"
        required: true
        type: "string"
      - name: "new_status"
        in: "path"
        description: "new status as Active/Disabled/Withdrawn"
        required: true
        type: "string"
      responses:
        201:
          description: "Returns created CSR"
          schema:
            $ref: '#/definitions/StatusChangeReply'
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"


definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI

  SLR_raw:
    type: "object"
    properties:
      protected:
        type: "string"
      payload:
        type: "string"
      signatures:
        type: array
        items:
          type: object

  SLR_content:
   type: "object"
   properties:
    attributes:
      $ref: '#/definitions/SLR_raw'
    type:
      type: "string"
    id:
      type: "string"

  SSR_content:
   type: "object"
   properties:
    attributes:
      type: "object"
      properties:
        header:
          type: "object"
        protected:
          type: "string"
        payload:
          type: "string"
        signature:
          type: "string"
    type:
      type: "string"
    id:
      type: "string"

  SSR:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/SSR_content"

  StatusChangeReply:
    type: object
    properties:
      data:
        type: object
        properties:
          attributes:
            type: object
          type:
            type: string
          id:
            type: string



  ConsentFormPOSTReply:
      type: object
      properties:
        sink_cr_id:
          type: string
          description: CR id for sink
        source_cr_id:
          type: integer
          description: CR id for source

  DataSet_Sink:
    type: object
    properties:
      publisher:
        type: string
        description: string containing publisher
      description:
        type: string
        description: string containing description
      keyword:
        type: array
        items:
          type: string
      title:
        type: string
        description: string containing title
      purposes:
        type: array
        items:
          type: object
          properties:
            required:
              type: boolean
              description: boolean containing required
            selected:
              type: boolean
              description: boolean containing selected
            title:
              type: string
              description: string containing title

      datase_id:
        type: string
        description: string containing datase_id

  DataSet_Source:
    type: "object"
    properties:
      publisher:
        type: string
        description: string containing publisher
      description:
        type: string
        description: string containing description
      keyword:
        type: array
        items:
          type: string


      title:
        type: string
        description: string containing title
      component_specification_label:
        type: string
        description: string containing component_specification_label
      distribution:
        type: object
        properties:
          distribution_id:
            type: string
            description: string containing distribution_id
          access_url:
            type: string
            description: string containing access_url
      selected:
        type: boolean
        description: boolean containing selected
      datase_id:
        type: string
        description: string containing datase_id



  Consent_FormReply:
    type: "object"
    properties:
      source:
        type: "object"
        properties:
          service_id:
            type: string
            description: string containing service_id
          rs_id:
            type: string
            description: string containing rs_id
          dataset:
            type: array
            items:
              $ref: "#/definitions/DataSet_Source"
      sink:
        type: "object"
        properties:
          service_id:
            type: string
            description: string containing service_id
          dataset:
            type: array
            items:
              $ref: "#/definitions/DataSet_Sink"